name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Show Context
      env:
        GITHUB_JSON: ${{ toJson(github) }}
      run: echo "{GITHUB_JSON}"
    - name: make
      run: make
    - name: make run
      run: make run
